// SPDX-FileCopyrightText: 2026 Scott Friedman
// SPDX-License-Identifier: Apache-2.0

// Package iac generates Infrastructure-as-Code artifacts for ground stacks.
// Three output formats are supported:
//   - cloudformation (default): JSON templates, deployed via ground deploy
//   - terraform: HCL for hashicorp/aws ~> 5.0, applied with terraform apply
//   - cdk: TypeScript CDK v2, deployed with npm install && cdk deploy
//
// CloudFormation is the reference/deploy mode. Terraform and CDK are
// output-only — generate artifacts for operators who prefer those tools.
package iac

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/provabl/ground/internal/config"
)

// Format identifies the IaC output format.
type Format string

const (
	FormatCloudFormation Format = "cloudformation" // default — deploy directly
	FormatTerraform      Format = "terraform"       // generate HCL to ./ground-terraform/
	FormatCDK            Format = "cdk"             // generate TypeScript to ./ground-cdk/
)

// Generator produces IaC artifacts for a given output format.
type Generator struct {
	format    Format
	outputDir string
}

// NewGenerator creates an IaC generator.
func NewGenerator(format Format, outputDir string) *Generator {
	return &Generator{format: format, outputDir: outputDir}
}

// Generate produces IaC artifacts from the ground config.
// For Terraform and CDK, this writes files to outputDir and returns without
// deploying. For CloudFormation, callers use the stack packages directly.
func (g *Generator) Generate(cfg *config.Config) error {
	switch g.format {
	case FormatTerraform:
		return g.generateTerraform(cfg)
	case FormatCDK:
		return g.generateCDK(cfg)
	default:
		return fmt.Errorf("format %q is handled by the CloudFormation deployer, not the IaC generator", g.format)
	}
}

// --- Terraform ---------------------------------------------------------------

func (g *Generator) generateTerraform(cfg *config.Config) error {
	if err := os.MkdirAll(g.outputDir, 0o750); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("# SPDX-FileCopyrightText: 2026 Scott Friedman\n")
	b.WriteString("# SPDX-License-Identifier: Apache-2.0\n")
	b.WriteString("# Generated by ground. Do not edit manually.\n\n")

	b.WriteString(`terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "` + cfg.Org.Region + `"
}

variable "identity_center_instance_arn" {
  description = "IAM Identity Center instance ARN"
  type        = string
  default     = ""
}

data "aws_organizations_organization" "current" {}

locals {
  org_root_id  = data.aws_organizations_organization.current.roots[0].id
  managed_tags = {
    "managed-by"    = "ground"
    "ground:version" = "0.2.0"
  }
}

# ── Organizational Units ───────────────────────────────────────────────────

resource "aws_organizations_organizational_unit" "security" {
  name      = "Security"
  parent_id = local.org_root_id
  tags      = merge(local.managed_tags, { "ground:tier" = "security" })
}

resource "aws_organizations_organizational_unit" "infrastructure" {
  name      = "Infrastructure"
  parent_id = local.org_root_id
  tags      = merge(local.managed_tags, { "ground:tier" = "infrastructure" })
}

resource "aws_organizations_organizational_unit" "research" {
  name      = "Research"
  parent_id = local.org_root_id
  tags      = merge(local.managed_tags, { "ground:tier" = "research" })
}

resource "aws_organizations_organizational_unit" "sensitive_research" {
  name      = "SensitiveResearch"
  parent_id = local.org_root_id
  tags      = merge(local.managed_tags, { "ground:tier" = "sensitive" })
}

resource "aws_organizations_organizational_unit" "dod_cmmc" {
  name      = "DoD-CMMC"
  parent_id = local.org_root_id
  tags      = merge(local.managed_tags, { "ground:tier" = "dod" })
}

# Sub-OUs under SensitiveResearch
resource "aws_organizations_organizational_unit" "nih_genomic" {
  name      = "NIHGenomic"
  parent_id = aws_organizations_organizational_unit.sensitive_research.id
  tags      = merge(local.managed_tags, { "ground:tier" = "sensitive", "ground:data-scope" = "genomic" })
}

resource "aws_organizations_organizational_unit" "hipaa_research" {
  name      = "HIPAAResearch"
  parent_id = aws_organizations_organizational_unit.sensitive_research.id
  tags      = merge(local.managed_tags, { "ground:tier" = "sensitive", "ground:data-scope" = "phi" })
}

resource "aws_organizations_organizational_unit" "cui_research" {
  name      = "CUIResearch"
  parent_id = aws_organizations_organizational_unit.sensitive_research.id
  tags      = merge(local.managed_tags, { "ground:tier" = "sensitive", "ground:data-scope" = "cui" })
}

# ── IAM Identity Center Permission Sets ───────────────────────────────────

resource "aws_ssoadmin_permission_set" "ground_user" {
  count            = var.identity_center_instance_arn != "" ? 1 : 0
  name             = "GroundUser"
  description      = "Standard user access — Research OU"
  instance_arn     = var.identity_center_instance_arn
  session_duration = "PT1H"
  tags             = local.managed_tags
}

resource "aws_ssoadmin_permission_set" "ground_sensitive_user" {
  count            = var.identity_center_instance_arn != "" ? 1 : 0
  name             = "GroundSensitiveUser"
  description      = "Sensitive Research OU — FIDO2 MFA required, IP allowlist enforced"
  instance_arn     = var.identity_center_instance_arn
  session_duration = "PT1H"
  tags             = local.managed_tags
}

resource "aws_ssoadmin_permission_set" "ground_sre_admin" {
  count            = var.identity_center_instance_arn != "" ? 1 : 0
  name             = "GroundSREAdmin"
  description      = "SRE administrator — phishing-resistant MFA, all sessions logged"
  instance_arn     = var.identity_center_instance_arn
  session_duration = "PT1H"
  tags             = local.managed_tags
}

resource "aws_ssoadmin_permission_set" "ground_auditor" {
  count            = var.identity_center_instance_arn != "" ? 1 : 0
  name             = "GroundAuditor"
  description      = "Read-only auditor access — 8-hour session"
  instance_arn     = var.identity_center_instance_arn
  session_duration = "PT8H"
  tags             = local.managed_tags
}

# ── Outputs ───────────────────────────────────────────────────────────────

output "security_ou_id"           { value = aws_organizations_organizational_unit.security.id }
output "infrastructure_ou_id"     { value = aws_organizations_organizational_unit.infrastructure.id }
output "research_ou_id"           { value = aws_organizations_organizational_unit.research.id }
output "sensitive_research_ou_id" { value = aws_organizations_organizational_unit.sensitive_research.id }
output "dod_cmmc_ou_id"           { value = aws_organizations_organizational_unit.dod_cmmc.id }
output "nih_genomic_ou_id"        { value = aws_organizations_organizational_unit.nih_genomic.id }
output "hipaa_research_ou_id"     { value = aws_organizations_organizational_unit.hipaa_research.id }
output "cui_research_ou_id"       { value = aws_organizations_organizational_unit.cui_research.id }
`)

	if err := os.WriteFile(filepath.Join(g.outputDir, "main.tf"), []byte(b.String()), 0o640); err != nil {
		return fmt.Errorf("write main.tf: %w", err)
	}

	// README
	readme := "# ground Terraform\n\nGenerated by `ground deploy --output terraform`.\n\n" +
		"```bash\nterraform init\nterraform plan\nterraform apply\n```\n\n" +
		"Set `identity_center_instance_arn` variable to enable IAM Identity Center permission sets.\n"
	_ = os.WriteFile(filepath.Join(g.outputDir, "README.md"), []byte(readme), 0o640)

	return nil
}

// --- CDK TypeScript ----------------------------------------------------------

func (g *Generator) generateCDK(cfg *config.Config) error {
	if err := os.MkdirAll(g.outputDir, 0o750); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// stack.ts
	stack := `// SPDX-FileCopyrightText: 2026 Scott Friedman
// SPDX-License-Identifier: Apache-2.0
// Generated by ground. Do not edit manually.

import * as cdk from 'aws-cdk-lib';
import * as organizations from 'aws-cdk-lib/aws-organizations';
import * as sso from 'aws-cdk-lib/aws-sso';
import { Construct } from 'constructs';

export interface GroundFoundationProps extends cdk.StackProps {
  identityCenterInstanceArn?: string;
}

export class GroundFoundationStack extends cdk.Stack {
  public readonly securityOuId: string;
  public readonly sensitiveResearchOuId: string;

  constructor(scope: Construct, id: string, props: GroundFoundationProps = {}) {
    super(scope, id, props);

    const managedTags = [
      { key: 'managed-by', value: 'ground' },
      { key: 'ground:version', value: '0.2.0' },
    ];

    // ── Organizational Units ──────────────────────────────────────────────

    // The org root ID is obtained at deploy time via a custom resource.
    const orgRoot = new cdk.custom_resources.AwsCustomResource(this, 'OrgRoot', {
      onUpdate: {
        service: 'Organizations',
        action: 'listRoots',
        parameters: {},
        physicalResourceId: cdk.custom_resources.PhysicalResourceId.fromResponse('Roots.0.Id'),
      },
      policy: cdk.custom_resources.AwsCustomResourcePolicy.fromSdkCalls({
        resources: cdk.custom_resources.AwsCustomResourcePolicy.ANY_RESOURCE,
      }),
    });
    const rootId = orgRoot.getResponseField('Roots.0.Id');

    const securityOU = new organizations.CfnOrganizationalUnit(this, 'SecurityOU', {
      name: 'Security',
      parentId: rootId,
      tags: [...managedTags, { key: 'ground:tier', value: 'security' }],
    });

    const infrastructureOU = new organizations.CfnOrganizationalUnit(this, 'InfrastructureOU', {
      name: 'Infrastructure',
      parentId: rootId,
      tags: [...managedTags, { key: 'ground:tier', value: 'infrastructure' }],
    });

    const researchOU = new organizations.CfnOrganizationalUnit(this, 'ResearchOU', {
      name: 'Research',
      parentId: rootId,
      tags: [...managedTags, { key: 'ground:tier', value: 'research' }],
    });

    const sensitiveResearchOU = new organizations.CfnOrganizationalUnit(this, 'SensitiveResearchOU', {
      name: 'SensitiveResearch',
      parentId: rootId,
      tags: [...managedTags, { key: 'ground:tier', value: 'sensitive' }],
    });

    new organizations.CfnOrganizationalUnit(this, 'DoDCMMCOU', {
      name: 'DoD-CMMC',
      parentId: rootId,
      tags: [...managedTags, { key: 'ground:tier', value: 'dod' }],
    });

    // Sub-OUs under SensitiveResearch
    new organizations.CfnOrganizationalUnit(this, 'NIHGenomicOU', {
      name: 'NIHGenomic',
      parentId: sensitiveResearchOU.ref,
      tags: [...managedTags, { key: 'ground:tier', value: 'sensitive' }, { key: 'ground:data-scope', value: 'genomic' }],
    });
    new organizations.CfnOrganizationalUnit(this, 'HIPAAResearchOU', {
      name: 'HIPAAResearch',
      parentId: sensitiveResearchOU.ref,
      tags: [...managedTags, { key: 'ground:tier', value: 'sensitive' }, { key: 'ground:data-scope', value: 'phi' }],
    });
    new organizations.CfnOrganizationalUnit(this, 'CUIResearchOU', {
      name: 'CUIResearch',
      parentId: sensitiveResearchOU.ref,
      tags: [...managedTags, { key: 'ground:tier', value: 'sensitive' }, { key: 'ground:data-scope', value: 'cui' }],
    });

    this.securityOuId = securityOU.ref;
    this.sensitiveResearchOuId = sensitiveResearchOU.ref;

    // ── IAM Identity Center Permission Sets (optional) ────────────────────

    if (props.identityCenterInstanceArn) {
      new sso.CfnPermissionSet(this, 'GroundUser', {
        instanceArn: props.identityCenterInstanceArn,
        name: 'GroundUser',
        description: 'Standard user access — Research OU',
        sessionDuration: 'PT1H',
        tags: managedTags,
      });

      new sso.CfnPermissionSet(this, 'GroundSensitiveUser', {
        instanceArn: props.identityCenterInstanceArn,
        name: 'GroundSensitiveUser',
        description: 'Sensitive Research OU — FIDO2 MFA required, IP allowlist enforced',
        sessionDuration: 'PT1H',
        tags: managedTags,
      });

      new sso.CfnPermissionSet(this, 'GroundSREAdmin', {
        instanceArn: props.identityCenterInstanceArn,
        name: 'GroundSREAdmin',
        description: 'SRE administrator — phishing-resistant MFA, all sessions logged',
        sessionDuration: 'PT1H',
        tags: managedTags,
      });

      new sso.CfnPermissionSet(this, 'GroundAuditor', {
        instanceArn: props.identityCenterInstanceArn,
        name: 'GroundAuditor',
        description: 'Read-only auditor — 8-hour session',
        sessionDuration: 'PT8H',
        tags: managedTags,
      });
    }

    // ── Stack Outputs ─────────────────────────────────────────────────────
    new cdk.CfnOutput(this, 'SecurityOuId',           { value: securityOU.ref });
    new cdk.CfnOutput(this, 'SensitiveResearchOuId',  { value: sensitiveResearchOU.ref });
    new cdk.CfnOutput(this, 'InfrastructureOuId',     { value: infrastructureOU.ref });
    new cdk.CfnOutput(this, 'ResearchOuId',           { value: researchOU.ref });
  }
}

const app = new cdk.App();
new GroundFoundationStack(app, 'GroundFoundationStack', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region:  process.env.CDK_DEFAULT_REGION ?? '` + cfg.Org.Region + `',
  },
  identityCenterInstanceArn: process.env.IDENTITY_CENTER_INSTANCE_ARN,
});
`

	packageJSON := `{
  "name": "ground-foundation",
  "version": "0.2.0",
  "description": "ground IaC — AWS Organizations OU hierarchy and IAM Identity Center permission sets",
  "scripts": {
    "build": "tsc",
    "cdk": "cdk"
  },
  "dependencies": {
    "aws-cdk-lib": "^2.100.0",
    "constructs": "^10.0.0"
  },
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  }
}
`
	cdkJSON := `{
  "app": "npx ts-node stack.ts",
  "context": {
    "@aws-cdk/core:enablePartitionLiterals": true
  }
}
`
	tsconfig := `{
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "lib": ["es2018"],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "outDir": "dist"
  },
  "exclude": ["node_modules", "dist"]
}
`
	readme := "# ground CDK\n\nGenerated by `ground deploy --output cdk`.\n\n" +
		"```bash\nnpm install\nnpm run build\ncdk diff\ncdk deploy\n```\n\n" +
		"Set `IDENTITY_CENTER_INSTANCE_ARN` environment variable to deploy permission sets.\n"

	for name, content := range map[string]string{
		"stack.ts":     stack,
		"package.json": packageJSON,
		"cdk.json":     cdkJSON,
		"tsconfig.json": tsconfig,
		"README.md":    readme,
	} {
		if err := os.WriteFile(filepath.Join(g.outputDir, name), []byte(content), 0o640); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}
